---
openapi: 3.0.0
info:
  description: powered by Flasgger
  termsOfService: /tos
  title: A swagger API
  version: 0.0.1
paths:
  /contacts:
    post:
      summary: Создание нового контакта
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Контакт успешно создан
components:
  schemas:
    Contact:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
