definitions: {}
info:
  description: powered by Flasgger
  termsOfService: /tos
  title: A swagger API
  version: 0.0.1
paths:
  /contacts:
    post:
      parameters:
      - in: body
        name: contact
        required: true
        schema:
          properties:
            name:
              type: string
            phone:
              type: string
          type: object
      responses:
        '200':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0443\u0441\u043F\
            \u0435\u0448\u043D\u043E \u0441\u043E\u0437\u0434\u0430\u043D"
      summary: "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043D\u043E\u0432\
        \u043E\u0433\u043E \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
swagger: '2.0'
