name: CI Workflow

on:
  push:
    branches:
      - main  # workflow срабатывает на пуш в ветку main

jobs:
  security_check:
    name: Security Check with Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4  # Проверяем код из репозитория

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Указываем нужную версию Python

      - name: Install Bandit
        run: |
          pip install bandit  # Устанавливаем Bandit для проверки безопасности

      - name: Run security check
        run: |
         bandit -r . -x ./venv -x ./.git --exclude ./venv/Lib/site-packages --skip B101,B110,B602,B603,B605,B607

      - name: Upload Bandit Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report  # Загрузка отчета Bandit как артефакт
          path: bandit_report.html  # Путь к отчету Bandit

  openapi_generation:
    name: Generate OpenAPI Documentation
    runs-on: ubuntu-latest
    needs: security_check  # Этот шаг зависит от завершения предыдущего шага

    steps:
      - name: Check out the code
        uses: actions/checkout@v4  # Проверяем код

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Указываем нужную версию Python

      - name: Install Dependencies
        run: |
          pip install flask flasgger  # Устанавливаем Flask и Flasgger для работы с OpenAPI

      - name: Run Flask application in background
        run: |
          export FLASK_APP=app.py  # Указываем правильный файл Flask-приложения
          flask run --host=0.0.0.0 --port=5000 --debug &  # Запускаем сервер в фоне с флагом debug

      - name: Wait for Flask to start
        run: sleep 10  # Увеличиваем время ожидания до 30 секунд

      - name: Generate OpenAPI Specification (openapi.yaml)
        run: |
          curl http://127.0.0.1:5000/swagger.json -o openapi.yaml  # Получаем OpenAPI спецификацию

      - name: Upload OpenAPI Spec as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec  # Загрузка OpenAPI спецификации как артефакт
          path: openapi.yaml  # Путь к сгенерированному файлу openapi.yaml

  redoc_generation:
    name: Generate ReDoc Page
    runs-on: ubuntu-latest
    needs: openapi_generation  # Этот шаг зависит от завершения предыдущего шага

    steps:
      - name: Check out the code
        uses: actions/checkout@v4  # Проверяем код

      - name: Install Node.js
        uses: actions/setup-node@v4
     










