name: Deploy API Documentation

on:
  push:
    branches:
      - main  # Workflow запускается при push в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask
          pip install flasgger  # Устанавливаем flasgger для генерации OpenAPI спецификации

      - name: Generate OpenAPI specification
        run: |
          # Запуск скрипта для генерации openapi.yaml
          python ./scrippt.py  # Используем относительный путь

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Redocly CLI
        run: |
          npm install -g @redocly/cli@latest

      - name: Generate ReDoc documentation
        run: |
          redocly build-docs ./docs/openapi.yaml --output ./docs/index.html  # Генерация документации в ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Публикуем сгенерированную документацию на GitHub Pages






