name: Deploy API Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Разрешение на запись
  pages: write      # Разрешение на публикацию на GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask
          pip install flasgger

      - name: Generate OpenAPI specification
        run: |
          python ./scrippt.py

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Redocly CLI
        run: |
          npm install -g @redocly/cli@latest

      - name: Generate ReDoc documentation
        run: |
          redocly build-docs ./docs/openapi.yaml --output ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен передается в action
          publish_dir: ./docs
git add .github/workflows/deploy.yml






