name: Deploy API Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask
          pip install flasgger

      - name: Generate OpenAPI specification
        run: |
          nohup python app.py &
          sleep 5
          curl http://127.0.0.1:5000/apidocs/swagger.json -o openapi.json
          mv openapi.json openapi.yaml

      # Установка пакета для конвертации YAML в JSON
      - name: Install yamljs for YAML to JSON conversion
        run: npm install -g yamljs

      # Преобразуем YAML в JSON
      - name: Convert YAML to JSON
        run: |
          yaml2json openapi.yaml > openapi.json

      # Устанавливаем и используем Redocly CLI для генерации документации
      - name: Install @redocly/cli
        run: npm install -g @redocly/cli

      - name: Generate ReDoc documentation
        run: |
          npx @redocly/cli build-docs openapi.json --output ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

